# Generated by Django 5.1.1 on 2024-09-19 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_trainings', to='sports.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='training',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.field'),
        ),
        migrations.AlterField(
            model_name='training',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.sport'),
        ),
    ]
