# Generated by Django 5.1.1 on 2024-09-23 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sports", "0003_remove_training_creator_alter_training_field_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="training",
            name="creator",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_trainings",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
